### ISSUE TITLE
Loading Error

### ISSUE THREAD

**Issue by DirtyVenomPSN** [BT-Industries/Maritime-Pack-2.0#1]
Stops loading at Maritime Pack/Clipper Parts/Engine1/part/FS_ClipperEngine1
![loadingfail](https://cloud.githubusercontent.com/assets/18096945/14850427/770cde02-0c25-11e6-87ec-2b420ca10286.PNG)

**Comment by BenjaminObermoser** [comment]
Hmmmm.
Are you running any other Mods?

I'll see what I can do, when I find some time.

**Comment by DirtyVenomPSN** [comment]
Mod List for the error:
![modsloadingerror](https://cloud.githubusercontent.com/assets/18096945/14850506/0ce1ec92-0c26-11e6-8f9f-eab042d74cea.PNG)
Anything with "DV" in it is the parts I modified myself..

**Comment by DirtyVenomPSN** [comment]
Anything with "DV" in it are my own custom modified parts.

**Comment by BenjaminObermoser** [comment]
I currently have no idea what it could be.

Maybe there is an issue with having a engine and an intake in one part.

Your custom mid edits look interesting.

Is the Dv carrier a modified Maritime Pack part or not?

**Comment by DirtyVenomPSN** [comment]
DV Carrier is modified Large ships, simple texture change, moving the engine part to a non-gamedata folder fixes it, and if that was the problem then KAX wouldn't be working either, but it does.

**Comment by BenjaminObermoser** [comment]
Sorry I meant "custom mod edits".

**Comment by DirtyVenomPSN** [comment]
Thanks, by the way.

**Comment by BenjaminObermoser** [comment]
Hmmm that's strange maybe I'll just do a folder rearrangement.

I'll check out the KAX engines and see if its just a problem in the . Cfg

**Comment by BenjaminObermoser** [comment]
Your welcome.
And thank you for testing it.

**Comment by DirtyVenomPSN** [comment]
Alright. And uh, if you want to add me on Skype so we can keep in better communication and more of an instant communication method, it's literally the exact same as my username here, minus the "PSN" part.

**Comment by DirtyVenomPSN** [comment]
No problem.

**Comment by BenjaminObermoser** [comment]
Okay good idea.
Keep posting issues you find on here so I can keep track though.

Just a small problem 

I don't have a Skype account

Would Google Hangouts work for you?
The rest of the team and I have a group chat going there.

If so send me your email address over the forum private message system (so not everyone can see it)

If not, that's okay I'll create a Skype account

**Comment by DirtyVenomPSN** [comment]
I mean, google hangouts would be fine if I knew how they actually worked, plus Skype is more convenient for me because I've been using it for a while and it's extremely user friendly... Plus I have no idea how to PM on github.

**Comment by BenjaminObermoser** [comment]
Skype it is then

Might take awhile computers got a drive error, currently working from my phone and I should probably get some sleep soon...

Thanks for your help

**Comment by DirtyVenomPSN** [comment]
Yet again, no problem at all. Always up to help the mod because as I said, along with BDA, Boat Parts and Skillful, it's one of my favorites.

**Comment by BenjaminObermoser** [comment]
Glad to hear it

Good night (At least from my perspective)

**Comment by DirtyVenomPSN** [comment]
'Night. Even though for me it's 4 in the morning.

**Comment by DirtyVenomPSN** [comment]
Still waiting on that Skype add, m8

**Comment by tahoe-vegas** [comment]
Had this issue too on 64-bit Windows, fixed by deleting the engine.

**Comment by DirtyVenomPSN** [comment]
@renoplane We already know. I'm working on editing the .cfg for it to attempt to fix it.

**Comment by BenjaminObermoser** [comment]
@renoplane 

Thanks for testing it out.

**Comment by CliftonMarien** [comment]
Fixed in the latest commit.
